/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo.tp.pkg13;

import javax.swing.*;
import java.sql.*;
import java.time.LocalDate;

/**
 *
 * @author Fathan
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogTambahPegawai = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        btnCancelTambahPegawai = new javax.swing.JButton();
        btnSaveTambahPegawai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textFieldNameTambahPegawai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        radioGeneralTambahPegawai = new javax.swing.JRadioButton();
        radioSergeantTambahPegawai = new javax.swing.JRadioButton();
        radioCorporalTambahPegawai = new javax.swing.JRadioButton();
        comboYearTambahPegawai = new javax.swing.JComboBox<>();
        comboMonthTambahPegawai = new javax.swing.JComboBox<>();
        comboDateTambahPegawai = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        radioGroupPosisiTambahPegawai = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPegawai = new javax.swing.JList<>();
        labelDaftarPegawai = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelPosisi = new javax.swing.JLabel();
        labelLahir = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTambahPegawai = new javax.swing.JButton();

        dialogTambahPegawai.setAlwaysOnTop(true);
        dialogTambahPegawai.setResizable(false);
        dialogTambahPegawai.setSize(new java.awt.Dimension(400, 344));

        btnCancelTambahPegawai.setText("Batal");
        btnCancelTambahPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelTambahPegawaiActionPerformed(evt);
            }
        });

        btnSaveTambahPegawai.setText("Simpan");
        btnSaveTambahPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTambahPegawaiActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama:");

        jLabel2.setText("Posisi:");

        radioGroupPosisiTambahPegawai.add(radioGeneralTambahPegawai);
        radioGeneralTambahPegawai.setText("General");

        radioGroupPosisiTambahPegawai.add(radioSergeantTambahPegawai);
        radioSergeantTambahPegawai.setText("Sergeant");

        radioGroupPosisiTambahPegawai.add(radioCorporalTambahPegawai);
        radioCorporalTambahPegawai.setText("Corporal");

        comboYearTambahPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1999", "2000", "2001", "2002", "2003", "2004", "2005" }));

        comboMonthTambahPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Okt", "Sept", "Nov", "Des" }));

        comboDateTambahPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel3.setText("Tanggal Lahir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNameTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelTambahPegawai)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioGeneralTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioSergeantTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSaveTambahPegawai)
                            .addComponent(radioCorporalTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboDateTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboMonthTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(comboYearTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNameTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioGeneralTambahPegawai)
                    .addComponent(radioSergeantTambahPegawai)
                    .addComponent(radioCorporalTambahPegawai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboYearTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMonthTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDateTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveTambahPegawai)
                    .addComponent(btnCancelTambahPegawai))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout dialogTambahPegawaiLayout = new javax.swing.GroupLayout(dialogTambahPegawai.getContentPane());
        dialogTambahPegawai.getContentPane().setLayout(dialogTambahPegawaiLayout);
        dialogTambahPegawaiLayout.setHorizontalGroup(
            dialogTambahPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTambahPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialogTambahPegawaiLayout.setVerticalGroup(
            dialogTambahPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTambahPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TP MODUL 13");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        listPegawai.setModel(new DefaultListModel());
        listPegawai.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPegawaiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPegawai);

        labelDaftarPegawai.setText("Daftar Pegawai");

        labelNama.setText("Nama:");

        labelPosisi.setText("Posisi:");

        labelLahir.setText("Tgl Lahir:");

        btnUbah.setText("Ubah");
        btnUbah.setEnabled(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTambahPegawai.setText("Tambah");
        btnTambahPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPegawaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelDaftarPegawai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambahPegawai))
                    .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPosisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDaftarPegawai)
                            .addComponent(btnTambahPegawai))
                        .addGap(15, 15, 15)
                        .addComponent(labelNama)
                        .addGap(47, 47, 47)
                        .addComponent(labelPosisi)
                        .addGap(51, 51, 51)
                        .addComponent(labelLahir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            Connection connection = SQLConnector.getInstance().getConnection();

            PreparedStatement s = connection.prepareStatement("SELECT * FROM pegawai;");
            ResultSet rs = s.executeQuery();

            while (rs.next()){
                Pegawai pegawai = new Pegawai();
                pegawai.setId(rs.getInt(1));
                pegawai.setName(rs.getString(2));
                pegawai.setPosisi(rs.getString(3));
                pegawai.setTglLahir(rs.getDate(4));

                DefaultListModel<Pegawai> model = (DefaultListModel<Pegawai>) listPegawai.getModel();
                model.addElement(pegawai);
            }

            connection.close();
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void listPegawaiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPegawaiValueChanged
        // TODO add your handling code here:
        Pegawai pegawai = listPegawai.getSelectedValue();
        if (pegawai == null){
            labelNama.setText("Nama: ");
            labelPosisi.setText("Posisi: ");
            labelLahir.setText("Tgl Lahir: ");
            
            btnHapus.setEnabled(false);
            btnUbah.setEnabled(false);
            return;
        }

       labelNama.setText("Nama: " + pegawai.getName());
       labelPosisi.setText("Posisi: " + pegawai.getPosisi());
       labelLahir.setText("Tgl Lahir: " + pegawai.getTglLahir());

       btnHapus.setEnabled(true);
       btnUbah.setEnabled(true);
    }//GEN-LAST:event_listPegawaiValueChanged

    private void btnTambahPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPegawaiActionPerformed
        dialogTambahPegawai.setVisible(true);
    }//GEN-LAST:event_btnTambahPegawaiActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        Pegawai selectedObj = listPegawai.getSelectedValue();
        int selected = listPegawai.getSelectedIndex();
        
        DefaultListModel<Pegawai> model = (DefaultListModel<Pegawai>) listPegawai.getModel();
        model.remove(selected);
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCancelTambahPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelTambahPegawaiActionPerformed
        dialogTambahPegawai.dispose();
    }//GEN-LAST:event_btnCancelTambahPegawaiActionPerformed

    private void btnSaveTambahPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTambahPegawaiActionPerformed
        // TODO add your handling code here:
        String nama = textFieldNameTambahPegawai.getText();
        String posisi = null;
        if (radioGeneralTambahPegawai.isSelected()){
            posisi = "General";
        }else if (radioSergeantTambahPegawai.isSelected()){
            posisi = "Sergeant";
        }else if (radioCorporalTambahPegawai.isSelected()){
            posisi = "Corporal";
        }
        
        String day = comboDateTambahPegawai.getSelectedItem().toString(),
                month = comboMonthTambahPegawai.getSelectedIndex() + "",
                year = comboYearTambahPegawai.getSelectedItem().toString();
        
        int d = Integer.parseInt(day);
        int m = Integer.parseInt(month + 1);
        int y = Integer.parseInt(year);
        
        Date date = Date.valueOf(LocalDate.of(y, m, d));
        
        int id = listPegawai.getModel().getSize() + 1;
        Pegawai pegawai = new Pegawai();
        
        pegawai.setId(id);
        pegawai.setName(nama);
        pegawai.setPosisi(posisi);
        pegawai.setTglLahir(date);
        
        DefaultListModel<Pegawai> model = (DefaultListModel<Pegawai>) listPegawai.getModel();
        model.addElement(pegawai);
        
        dialogTambahPegawai.setVisible(false);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
    }//GEN-LAST:event_btnSaveTambahPegawaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelTambahPegawai;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSaveTambahPegawai;
    private javax.swing.JButton btnTambahPegawai;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> comboDateTambahPegawai;
    private javax.swing.JComboBox<String> comboMonthTambahPegawai;
    private javax.swing.JComboBox<String> comboYearTambahPegawai;
    private javax.swing.JDialog dialogTambahPegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDaftarPegawai;
    private javax.swing.JLabel labelLahir;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPosisi;
    private javax.swing.JList<Pegawai> listPegawai;
    private javax.swing.JRadioButton radioCorporalTambahPegawai;
    private javax.swing.JRadioButton radioGeneralTambahPegawai;
    private javax.swing.ButtonGroup radioGroupPosisiTambahPegawai;
    private javax.swing.JRadioButton radioSergeantTambahPegawai;
    private javax.swing.JTextField textFieldNameTambahPegawai;
    // End of variables declaration//GEN-END:variables
}
